No intermediate rootfs.img
Completely replace dmsquash-live with our ostree-live and directly mount
the squash file system without the intermediate rootfs.img

This will result in lower storage needs for the live images,
faster startup and we are in control of the boot process with our
custom dracut module.

See also [1] from ostree-image-creator issues.

[1] https://github.com/lirios/ostree-image-creator/issues/4

diff --git a/overlay.d/05live/usr/lib/dracut/modules.d/20ostree-live/ostree-live-generator b/overlay.d/05live/usr/lib/dracut/modules.d/20ostree-live/ostree-live-generator
--- a/overlay.d/05live/usr/lib/dracut/modules.d/20ostree-live/ostree-live-generator
+++ b/overlay.d/05live/usr/lib/dracut/modules.d/20ostree-live/ostree-live-generator
@@ -2,9 +2,12 @@
 
 command -v getarg >/dev/null || . /usr/lib/dracut-lib.sh
 
-set -e
-
-UNIT_DIR="${1:-/tmp}"
+UNIT_DIR="$1"
+if [ -z "${UNIT_DIR}" ]; then
+    echo "$0: missing argument"
+    exit 1
+fi
+[ -d "${UNIT_DIR}" ] || mkdir -p "${UNIT_DIR}"
 
 add_requires() {
     local name="$1"
@@ -13,18 +16,59 @@ add_requires() {
     ln -sf "../${name}" "${requires_dir}/${name}"
 }
 
-is_live=$(getargbool 0 oic.live)
-iso_label=$(getarg oic.live.label=)
+if getargbool 0 rd.live.debug -n -y rdlivedebug; then
+    exec > /tmp/liveroot.$$.out
+    exec 2>> /tmp/liveroot.$$.out
+    set -x
+fi
 
-if getargbool 0 oic.live; then
-    # Create stamp file that everything else should use to detect a live boot
-    > /run/ostree-live
+if ! getargbool 0 rd.live.image; then
+    echo "$0: skipping due to missing rd.live.image argument"
+    exit 0
+fi
 
-    add_requires sysroot.mount
-    add_requires sysroot-var.mount
+live_dir=$(getarg rd.live.dir -d live_dir)
+[ -z "$live_dir" ] && live_dir="LiveOS"
+squash_image=$(getarg rd.live.squashimg)
+[ -z "$squash_image" ] && squash_image="squashfs.img"
 
-    if [ -n "${iso_label}" ]; then
-        cat > "${UNIT_DIR}/run-initramfs-live.mount" <<EOF
+iso_label=$(getarg oic.live.label)
+if [ -z "$iso_label" ]; then
+    echo "$0: missing oic.live.label argument, cannot continue!"
+    exit 1
+fi
+
+# Create stamp file that everything else should use to detect a live boot
+> /run/ostree-live
+
+# MD5 check
+cdrom_devname=$(dev_unit_name "/dev/disk/by-label/${iso_label}")
+cat > "${UNIT_DIR}/checkisomd5.service" <<EOF
+[Unit]
+Description=Media check on ${cdrom_devname}
+DefaultDependencies=no
+Before=shutdown.target
+ConditionKernelCommandLine=rd.live.check
+
+[Service]
+Type=oneshot
+RemainAfterExit=no
+ExecStartPre=-/bin/plymouth hide-splash
+ExecStart=/bin/checkisomd5 --verbose ${cdrom_devname}
+ExecStartPost=-/bin/plymouth show-splash
+StandardInput=tty-force
+StandardOutput=inherit
+StandardError=inherit
+TimeoutSec=0
+SuccessExitStatus=2
+EOF
+
+# Install mount units
+add_requires sysroot.mount
+add_requires sysroot-var.mount
+
+# Mount ISO image
+cat > "${UNIT_DIR}/run-initramfs-live.mount" <<EOF
 # Automatically generated by ostree-live-generator
 
 [Unit]
@@ -36,7 +80,8 @@ Where=/run/initramfs/live
 Type=iso9660
 EOF
 
-        cat > "${UNITDIR}/sysroot.mount" <<EOF
+# Mount /sysroot
+cat > "${UNIT_DIR}/sysroot.mount" <<EOF
 # Automatically generated by ostree-live-generator
 
 [Unit]
@@ -45,15 +90,14 @@ Before=initrd-root-fs.target
 Requires=run-initramfs-live.mount
 
 [Mount]
-What=/run/initramfs/live/LiveOS/squashfs.img
+What=/run/initramfs/live/${live_dir}/${squash_image}
 Where=/sysroot
 Type=squashfs
 EOF
-    fi
 
-    # Add ostree= to the kernel command line before ostree-prepare-root
-    mkdir -p "${UNIT_DIR}/ostree-prepare-root.service.d"
-    cat > "${UNIT_DIR}/ostree-prepare-root.service.d/10-live.conf" <<EOF
+# Add ostree= to the kernel command line before ostree-prepare-root
+mkdir -p "${UNIT_DIR}/ostree-prepare-root.service.d"
+cat > "${UNIT_DIR}/ostree-prepare-root.service.d/10-live.conf" <<EOF
 # Automatically generated by ostree-live-generator
 
 [Unit]
@@ -66,8 +110,8 @@ ExecStartPre=/usr/sbin/ostree-cmdline start
 ExecStartPost=/usr/sbin/ostree-cmdline stop
 EOF
 
-    # Writable area
-    cat > "${UNIT_DIR}/writable.mount" <<EOF
+# Writable area
+cat > "${UNIT_DIR}/writable.mount" <<EOF
 # Automatically generated by ostree-live-generator
 
 [Unit]
@@ -82,8 +126,8 @@ Type=tmpfs
 Options=mode=0700
 EOF
 
-    # Store /sysroot/var in the /writable tmpfs
-    cat > "${UNIT_DIR}/sysroot-var.mount" <<EOF
+# Store /sysroot/var in the /writable tmpfs
+cat > "${UNIT_DIR}/sysroot-var.mount" <<EOF
 # Automatically generated by ostree-live-generator
 
 [Unit]
@@ -92,9 +136,6 @@ DefaultDependencies=false
 # Make sure /sysroot is mounted first, since we're mounting under there
 Requires=initrd-root-fs.target
 After=initrd-root-fs.target
-
-# Needs /sysroot
-RequiresMountsFor=/sysroot
 
 # Make sure our tmpfs is available
 RequiresMountsFor=/writable
@@ -105,4 +146,3 @@ Where=/sysroot/var
 Type=none
 Options=bind
 EOF
-fi
